language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: davidfriar.surge.sh
  project: ./public/
